# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'BitcoinDemo' do
  pod 'SnapKit', '~> 5.6.0'
  pod 'Bitcoin-alpha', '~> 1.0.0'
end
